version: '3.9'

services:
  dev-db:
    image: postgres:12.7
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_DB=nestjs-cookies-auth
    ports:
      - 5432:5432
